apiVersion: v1
kind: Service
metadata:
  name: cards-matching-primary-service
spec:
  type: NodePort
  selector:
    app: cards-matching
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 31002
