apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-matching-primary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-matching
      role: primary
  template:
    metadata:
      labels:
        app: cards-matching
        role: primary
    spec:
      containers:
      - name: cards-matching-primary
        image: architecture_games-cards_matching
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health
            port: 5002

