apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Optionally specify a storageClassName if needed by your environment:
  # storageClassName: "standard"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-primary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      role: primary
  template:
    metadata:
      labels:
        app: mongodb
        role: primary
    spec:
      containers:
        - name: mongodb-primary
          image: mongo:6.0
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db  # MongoDB’s default data dir
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
