apiVersion: v1
kind: Service
metadata:
  name: mastermind-backup-service
spec:
  type: NodePort
  selector:
    app: mastermind
    role: backup
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32001
