apiVersion: v1
kind: Service
metadata:
  name: mastermind-primary-service
spec:
  selector:
    app: mastermind
  ports:
    - port: 5004                        # Exposed port on the service
      targetPort: 5004                  # Container port to route traffic
  type: LoadBalancer                       # Internal access only (default)
