apiVersion: v1
kind: Service
metadata:
  name: mastermind-failover-service
spec:
  type: LoadBalancer
  selector:
    app: mastermind-failover
  ports:
    - protocol: TCP
      port: 90         # External port exposed to clients
      targetPort: 90
