apiVersion: v1
kind: Service
metadata:
  name: hangman-backup-service
spec:
  type: NodePort
  selector:
    app: hangman
    role: backup
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 32002
