apiVersion: v1
kind: Service
metadata:
  name: hangman-primary-service
spec:
  type: LoadBalancer
  selector:
    app: hangman
    role: primary
  ports:
    - port: 5003           # Service port
      targetPort: 5003     # Pod's container port
