apiVersion: v1
kind: Service
metadata:
  name: hangman-failover-service
spec:
  type: LoadBalancer
  selector:
    app: hangman-failover
  ports:
    - protocol: TCP
      port: 80         # External port exposed to clients
      targetPort: 80
