apiVersion: v1
kind: ConfigMap
metadata:
  name: hangman-failover-config
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      upstream hangman_upstream {
        server hangman-primary-service.default.svc.cluster.local:5003 ;
        server hangman-backup-service.default.svc.cluster.local:3002 backup;
      }
      server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass http://hangman_upstream;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          # Enable failover and retry logic
          proxy_next_upstream error timeout http_502 http_503 http_504;
          proxy_next_upstream_timeout 5s;
          proxy_next_upstream_tries 3;
        
        }
      }
    }
