apiVersion: v1
kind: ConfigMap
metadata:
  name: hangman-failover-config
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      upstream hangman_upstream {
        server localhost:31003 ;
        server localhost:32002 backup;
      }
      server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass http://hangman_upstream;
        }
      }
    }
